project/myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views as v
from myapp.views import AccountCreateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("board_create/", v.board_create, name="board_create"),
    path("board_list/", v.board_list, name="board_list"),
    path("accounts/", include("allauth.urls")),
    path("create/", AccountCreateView.as_view(), name="login_create"),
    path("", v.main, name="main"),
    path("login/", v.login_view, name="login"),
    path("accounts/", include("allauth.urls")),
    path("grow_1/", v.grow_1, name="grow_1"),
    path("like_post/<int:post_id>/", v.like_post, name="like_post"),
    path("dislike_post/<int:post_id>/", v.dislike_post, name="dislike_post"),
    path("mypage_share/", v.mypage_share, name="mypage_share"),
    path("search/", v.search_view, name="search"),
    path("mypage/", v.mypage_setting, name="mypage_setting"),
    path("signup/", v.signup, name="signup"),
    path("after_login/", v.after_login, name="after_login"),
    path("detail/<int:post_id>/", v.board_detail, name="board_detail"),
    path("detail/<int:post_id>/update/", v.update, name="update"),
    path("detail/<int:post_id>/delete/", v.delete, name="delete"),
    path("<int:pk>/comment/", v.comment_create, name="comment_create"),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/delete/",
        v.comment_delete,
        name="comment_delete",
    ),
    path("check-email", v.check_email, name="check-email"),
    path("add-friend", v.add_friend, name="add-friend"),
    path("grow-1/", v.grow_1_view, name="grow_1"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views as v
from myapp.views import AccountCreateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("board_create/", v.board_create, name="board_create"),
    path("board_list/", v.board_list, name="board_list"),
    path("accounts/", include("allauth.urls")),
    path("create/", AccountCreateView.as_view(), name="login_create"),
    path("", v.main, name="main"),
    path("board_create/", v.board_create, name="board_create"),
    path("login/", v.login_view, name="login"),
    path("board_list/", v.board_list, name="board_list"),
    path("accounts/", include("allauth.urls")),
    path("grow_1/", v.grow_1, name="grow_1"),
    path("like_post/<int:post_id>/", v.like_post, name="like_post"),
    path("dislike_post/<int:post_id>/", v.dislike_post, name="dislike_post"),
    path("post/<int:id>/", v.board_detail, name="board_detail"),  # URL이 올바른지 확인
    path("mypage_share/", v.mypage_share, name="mypage_share"),
    path("search/", v.search_view, name="search"),
    path("mypage_setting/", v.mypage_setting, name="mypage_setting"),
    path("signup/", v.signup, name="signup"),
    path("after_login/", v.after_login, name="after_login"),
    path("detail/<int:post_id>/", v.board_detail, name="board_detail"),
    path("detail/<int:post_id>/update/", v.update, name="update"),
    path("detail/<int:post_id>/delete/", v.delete, name="delete"),
    path("<int:pk>/comment/", v.comment_create, name="comment_create"),
    path(
        "<int:article_pk>/comment/<int:comment_pk>/delete/",
        v.comment_delete,
        name="comment_delete",
    ),
    path("logout/", v.logout_view, name="logout"),
    path(
        "detail/<int:post_id>/comment/", v.board_detail, name="comment_create"
    ),  # 댓글 작성 URL 추가
    path("grow_2/<int:post_id>/", v.grow_2, name="grow_2"),
    path("grow_3/<int:reflection_id>/", v.grow_3, name="grow_3"),
    path("save_reflection/<int:post_id>/", v.save_reflection, name="save_reflection"),
    path("reflection/<int:reflection_id>/", v.view_reflection, name="view_reflection"),
    path(
        "edit_reflection/<int:reflection_id>/",
        v.edit_reflection,
        name="edit_reflection",
    ),
    path(
        "delete_reflection/<int:reflection_id>/",
        v.delete_reflection,
        name="delete_reflection",
    ),
    path("check-email", v.check_email, name="check-email"),
    path("add-friend", v.add_friend, name="add-friend"),
    path("grow-1/", v.grow_1_view, name="grow_1"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings


class KakaoUser(models.Model):
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)
    nickname = models.CharField(max_length=100, blank=False)
    gender = models.CharField(max_length=10, blank=True)
    age_range = models.CharField(max_length=20, blank=True)
    email = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.nickname


class NaverUser(models.Model):
    user = models.OneToOneField("auth.User", on_delete=models.CASCADE)
    nickname = models.CharField(max_length=100, blank=False)
    gender = models.CharField(max_length=10, blank=True)
    age_range = models.CharField(max_length=20, blank=True)
    email = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return self.nickname


class BoardPost(models.Model):
    DEVELOPMENT_PERIOD_CHOICES = [
        ("0-3", "0~3개월"),
        ("4-7", "4~7개월"),
        ("8-11", "8~11개월"),
        ("12+", "12개월 이상"),
    ]

    PARTICIPANTS_CHOICES = [
        ("1-6", "1~6명"),
        ("7-12", "7~12명"),
        ("13-18", "13~18명"),
        ("19+", "19명 이상"),
    ]

    LANGUAGE_CHOICES = [
        ("python", "Python"),
        ("numpy", "Numpy"),
        ("pandas", "Pandas"),
        ("java", "Java"),
        ("javascript", "JavaScript"),
        ("django", "Django"),
        ("html", "HTML"),
        ("css", "CSS"),
        ("c++", "C++"),
        ("other", "직접입력"),
    ]

    title = models.CharField(max_length=200)
    content = models.TextField()
    development_period = models.CharField(
        max_length=5, choices=DEVELOPMENT_PERIOD_CHOICES
    )
    participants = models.CharField(max_length=6, choices=PARTICIPANTS_CHOICES)
    language = models.CharField(max_length=10, choices=LANGUAGE_CHOICES)
    file = models.ImageField(upload_to="uploads/", null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name="liked_posts", blank=True)
    dislikes = models.ManyToManyField(User, related_name="disliked_posts", blank=True)
    reflection_num = models.BooleanField(default=False)

    def __str__(self):
        return self.title


from django.db import models
from django.conf import settings


class Comment(models.Model):
    post = models.ForeignKey(
        "BoardPost", on_delete=models.CASCADE, related_name="comments", null=True
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content[:50]  # 댓글의 처음 20자만 표시


class Reflection(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(BoardPost, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # 회고록이 작성되었으므로 해당 게시물의 reflection 필드를 True로 설정
        self.post.reflection_num = True
        self.post.save()

    def __str__(self):
        return self.content[:50]


class Friendship(models.Model):
    creator = models.ForeignKey(
        User, related_name="friendship_creator_set", on_delete=models.CASCADE
    )
    friend = models.ForeignKey(
        User, related_name="friend_set", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.creator.username} is friends with {self.friend.username}"

project/myapp/forms.py
from django import forms
from .models import BoardPost, Comment


# class CommentForm(forms.ModelForm):

#     class Meta:
#         model = Comment
#         # fields = '__all__'
#         exclude = (
#             "boardpost",
#             "user",
#         )


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]  # 'post' 필드를 제외합니다.

from django import forms
from django.contrib.auth.forms import AuthenticationForm

class LoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ID'})
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'PASSWORD'})
    )

project/myapp/templates/after_login.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/after_login.css' %}">
    <title>after_login.html</title>
</head>
<body>
    <header id="header">
        <a href="{% url 'main' %}" id="header-logo">
            <img src="{% static 'img/white_logo.svg' %}" alt="로고 이미지" 
            style="
            height: 100px;
        "></a>
        <nav id="header-nav">
            <a href="{% url 'board_list' %}">공유용 게시판</a>
            <a href="{% if user.is_authenticated %}{% url 'grow_1' %}{% else %}{% url 'login' %}{% endif %}">성장관찰</a>
            <a href="{% if user.is_authenticated %}{% url 'after_login' %}{% else %}{% url 'login' %}{% endif %}">마이페이지</a>
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">로그아웃</a>
            {% endif %}
        </nav>
    </header>
    <main>
        <div class="logo-text">
            <img src="{% static 'img/IMG_0726.png' %}" width="350px">
        </div>
        <form class="form-container">
            <div class="form-text">
                <h2>{{ username }}</h2>
            </div>
            <div class="section">
                <a href="{% url 'mypage_share' %}" >회고용 게시물 공유</a>
            </div>
            <div class="section">
                <a href="{% url 'mypage_setting' %}" >환경 설정</a>
            </div>
            <div class="section" style="color:#048271;">
                계정 삭제
            </div>
        </form>
    </main>
</body>
</html>

project/myapp/templates/board_create.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/board_create.css' %}">
    <title>ProReflect</title>
</head>
<body>
    <header id="header">
        <a href="{% url 'main' %}" id="header-logo">
            <img src="{% static 'img/white_logo.svg' %}" alt="로고 이미지" 
            style="
            height: 100px;
        "></a>
        <nav id="header-nav">
            <a href="{% url 'board_list' %}">공유용 게시판</a>
            <a href="{% if user.is_authenticated %}{% url 'grow_1' %}{% else %}{% url 'login' %}{% endif %}">성장관찰</a>
            <a href="{% if user.is_authenticated %}{% url 'after_login' %}{% else %}{% url 'login' %}{% endif %}">마이페이지</a>
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">로그아웃</a>
            {% endif %}
        </nav>
    </header>
<main>
    <a href="{% url 'board_list' %}">
        <img src="{% static 'img/back-button.svg' %}" alt="뒤로가기 아이콘" class="back-btn-icon">
    </a>
    <form action="{% url 'board_create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h1 id="board-create-title">Reflect 작성</h1>
        <div id="board-create-top">
            <input type="text" id="board-create-post-title" name="title" placeholder="제목을 입력해 주세요.">      
            <button class="board-post-btn">Reflect 게시</button>
        </div>
        <div id="board-create-content">
            <textarea id="board-create-content-detail" name="content" placeholder="프로젝트의 목적, 개발 스택, 배포 링크, 깃허브 주소 등 개발했던 프로젝트와 관련된 이야기를 써주세요. 같이 프로젝트에 참여한 사람을 @멘션 해보세요!"></textarea>
            <input type="hidden" name="participants" id="participants_input">
            <input type="hidden" name="development_period" id="development_period_input">
            <input type="hidden" name="language" id="language_input">
            <input type="file" name="file" id="board-file-input" style="display:none;">
            <div id="board-create-setting-box">
                <!-- 개발 기간 드롭다운 -->
                <div class="board-create-dropdown">
                    <button class="board-create-dropdown-btn" onclick="toggleDropdown(); event.preventDefault()">
                        개발 기간
                        <img src="{% static 'img/inverted-triangle.svg' %}" alt="드롭다운 아이콘" class="board-create-dropdown-img">
                    </button>
                    <div class="board-create-dropdown-content">
                        <a href="#" onclick="selectOption('0-3', 'development_period_input', '.board-create-dropdown-btn'); event.preventDefault()">0~3개월</a>
                        <a href="#" onclick="selectOption('4-7', 'development_period_input', '.board-create-dropdown-btn'); event.preventDefault()">4~7개월</a>
                        <a href="#" onclick="selectOption('8-11', 'development_period_input', '.board-create-dropdown-btn'); event.preventDefault()">8~11개월</a>
                        <a href="#" onclick="selectOption('12+', 'development_period_input', '.board-create-dropdown-btn'); event.preventDefault()">12개월 이상</a>
                    </div>                    
                </div>

                <!-- 참여 인원 드롭다운 -->
                <div class="board-create-dropdown2">
                    <button class="board-create-dropdown-btn2" onclick="toggleDropdown2(); event.preventDefault()">
                        참여 인원
                        <img src="{% static 'img/inverted-triangle.svg' %}" alt="드롭다운 아이콘" class="board-create-dropdown-img">
                    </button>
                    <div class="board-create-dropdown-content2">
                        <a href="#" onclick="selectOption('1-6', 'participants_input', '.board-create-dropdown-btn2'); event.preventDefault()">1~6명</a>
                        <a href="#" onclick="selectOption('7-12', 'participants_input', '.board-create-dropdown-btn2'); event.preventDefault()">7~12명</a>
                        <a href="#" onclick="selectOption('13-18', 'participants_input', '.board-create-dropdown-btn2'); event.preventDefault()">13~18명</a>
                        <a href="#" onclick="selectOption('19+', 'participants_input', '.board-create-dropdown-btn2'); event.preventDefault()">19명 이상</a>
                    </div>                    
                </div>

                <!-- 사용 언어 드롭다운 -->
                <div class="board-create-dropdown">
                    <button class="board-create-dropdown-btn3" onclick="toggleDropdown3(); event.preventDefault()">
                        사용 언어
                        <img src="{% static 'img/inverted-triangle.svg' %}" alt="드롭다운 아이콘" class="board-create-dropdown-img">
                    </button>
                    <div class="board-create-dropdown-content3">
                        <a href="#" onclick="selectLanguage('python'); event.preventDefault()">Python</a>
                        <a href="#" onclick="selectLanguage('numpy'); event.preventDefault()">NumPy</a>
                        <a href="#" onclick="selectLanguage('pandas'); event.preventDefault()">Pandas</a>
                        <a href="#" onclick="selectLanguage('java'); event.preventDefault()">Java</a>
                        <a href="#" onclick="selectLanguage('javascript'); event.preventDefault()">JavaScript</a>
                        <a href="#" onclick="selectLanguage('django'); event.preventDefault()">Django</a>
                        <a href="#" onclick="selectLanguage('html'); event.preventDefault()">HTML</a>
                        <a href="#" onclick="selectLanguage('css'); event.preventDefault()">CSS</a>
                        <a href="#" onclick="selectLanguage('c++'); event.preventDefault()">C++</a>
                        <a href="#" onclick="selectLanguage('other'); event.preventDefault()">직접 입력</a>
                    </div>                    
                </div>
                
                <!-- 사용 언어 추가될 부분 -->
                <div id="board-create-selected-languages"></div>

                <!-- 파일 첨부 -->
                <div id="board-file-display"></div>
                <div class="board-create-img" onclick="boardFileInput()">
                    파일 첨부
                    <img src="{% static 'img/paperclip.svg' %}" alt="파일 첨부 아이콘">
                </div>
                <input type="file" name="file" id="board-file-input">
            </div>
        </div>
    </form>
</main>
    {% load static %}
    <script src="{% static 'js/board_create.js' %}"></script>
</body>
</html>

project/myapp/templates/board_detail.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/board_detail.css' %}">
    <title>ProReflect</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <style>
        .comments {
            margin: 20px 0; /* 수정함 */
            padding: 15px;
            background-color: #f9f9f9;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .comment {
            border-bottom: 1px solid #ccc;
            padding: 10px;
            margin-bottom: 10px;
        }
        .comment:last-child {
            border-bottom: none;
        }
        .comment strong {
            color: #333;
            font-size: 1.1em;
        }
        .comment p {
            margin: 5px 0;
            line-height: 1.5;
        }
        .comment-form textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            resize: vertical;
            height: 100px;
            margin: 10px 0; /* 수정함 */
        }
        .comment-form button {
            margin-bottom: 10px; /* 수정함 */
            padding: 10px 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            float: right;
        }
        .comment-form button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <header id="header">
        <a href="{% url 'main' %}" id="header-logo">
            <img src="{% static 'img/white_logo.svg' %}" alt="로고 이미지" 
            style="
            height: 100px;
        "></a>
        <nav id="header-nav">
            <a href="{% url 'board_list' %}">공유용 게시판</a>
            <a href="{% if user.is_authenticated %}{% url 'grow_1' %}{% else %}{% url 'login' %}{% endif %}">성장관찰</a>
            <a href="{% if user.is_authenticated %}{% url 'after_login' %}{% else %}{% url 'login' %}{% endif %}">마이페이지</a>
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">로그아웃</a>
            {% endif %}
        </nav>
    </header>
    <main>
        <a href="{% url 'main' %}">
            <img src="{% static 'img/back-button.svg' %}" alt="뒤로가기 아이콘" class="back-btn-icon">
        </a>
        <div class="board-detail-container">
            <h1 id="board-detail-title">{{ post.title }}</h1>
            <h3 id="board-detail-username">{{ post.user.username }}</h3>
            <div class="board-detail-top">
                <div id="board-detail-friends">
                    <!-- 참여한 친구들 표시 -->
                </div>
                <div id="board-detail-btns">
                    {% if request.user == post.user %}
                    <a href="{% url 'update' post.id %}">수정</a>
                    <a href="{% url 'delete' post.id %}">삭제</a>
                    {% endif %}
                </div>
            </div>
            <div id="board-detail-info-container">
                <div id="board-detail1"> <!-- 개발 기간이랑 참여 인원 -->
                    <div class="board-detail-info">{{ post.get_development_period_display }}</div>
                    <div class="board-detail-info">{{ post.get_participants_display }}</div>
                </div>
                {% load myapp_filters %}
                <div id="board-detail2">
                    {% if post.get_language_display %}
                    {% for language in post.get_language_display|split_string:',' %}
                        <div class="board-detail-info">{{ language|trim }}</div>
                    {% endfor %}
                    {% endif %}
                </div>
                
            </div>
            <div class="board-detail-bottom">
                {% if post.file %}
                    <img src="{{ post.file.url }}" alt="게시글 이미지" id="board-detail-img">
                {% else %}
                    <img src="{% static 'img/default_project_image.png' %}" alt="게시글 이미지" id="board-detail-img">
                {% endif %}
                <p id="board-detail-content">{{ post.content }}</p>
                <div class="board-detail-bottom-box">
                    <div class="board-detail-btn-container">
                        <button class="board-detail-btn" id="like-btn" data-post-id="{{ post.id }}">
                            <img src="{% static 'img/heart.svg' %}" alt="좋아요 버튼 아이콘">
                            <span class="likes-count">{{ post.likes.count }}</span>
                        </button>
                        <button class="board-detail-btn" id="dislike-btn" data-post-id="{{ post.id }}">
                            <img src="{% static 'img/water-drop.svg' %}" alt="아쉬워요 버튼 아이콘">
                            <span class="dislikes-count">{{ post.dislikes.count }}</span>
                        </button>
                    </div>
                    <h4>(최종수정 {{ post.updated_at|date:"Y.m.d" }}) {{ post.created_at|date:"Y.m.d" }}</h4>
                </div>
            </div>            
        </div>
        <!-- 댓글 섹션 -->
        <section class="comments">
            <h2>댓글</h2>
            {% for comment in comments %}
            <div class="comment">
                <strong>{{ comment.user.username }}</strong>
                <p>{{ comment.content }}</p>
                <p>작성 시간: {{ comment.created_at }}</p>
            </div>
            {% empty %}
            <p>댓글이 없습니다.</p>
            {% endfor %}
        </section>

        <!-- 댓글 작성 폼 -->
        <form action="{% url 'comment_create' post.id %}" method="post" class="comment-form">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit">댓글 작성</button>
        </form>
    </main>
    <script>
        $(document).ready(function() {
            function getCookie(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    const cookies = document.cookie.split(';');
                    for (let i = 0; i < cookies.length; i++) {
                        const cookie = jQuery.trim(cookies[i]);
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }
            const csrftoken = getCookie('csrftoken');
    
            function csrfSafeMethod(method) {
                return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                }
            });
    
            $('#like-btn').click(function() {
                var postId = $(this).data('post-id');
                $.ajax({
                    url: '/like_post/' + postId + '/',
                    method: 'POST',
                    contentType: 'application/json',  // Set content type to JSON
                    data: JSON.stringify({}),  // Send empty JSON object
                    success: function(response) {
                        $('.likes-count').text(response.likes);
                        $('#like-btn img').attr('src', response.liked ? '{% static "img/heart-clicked.svg" %}' : '{% static "img/heart.svg" %}');
                    },
                    error: function(xhr, status, error) {
                        console.error("Error: " + error);
                        console.error("Response: " + xhr.responseText);
                    }
                });
            });

            $('#dislike-btn').click(function() {
                var postId = $(this).data('post-id');
                $.ajax({
                    url: '/dislike_post/' + postId + '/',
                    method: 'POST',
                    contentType: 'application/json',  // Ensure the content-type is set to application/json
                    data: JSON.stringify({}),  // Sending an empty object as data
                    success: function(response) {
                        $('.dislikes-count').text(response.dislikes);
                        $('#dislike-btn img').attr('src', response.disliked ? '{% static "img/water-drop-clicked.svg" %}' : '{% static "img/water-drop.svg" %}');
                    },
                    error: function(xhr, status, error) {
                        console.error("Error: " + error);
                        console.error("Response: " + xhr.responseText);
                    }
                });
            });
        });
    </script>
</body>
</html>

project/myapp/templates/grow_3.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/grow_2.css' %}">
    <title>ProReflect</title>
</head>
<body>
    <header id="header">
        <a href="{% url 'main' %}" id="header-logo">
            <img src="{% static 'img/white_logo.svg' %}" alt="로고 이미지" 
            style="
            height: 100px;
        "></a>
        <nav id="header-nav">
            <a href="{% url 'board_list' %}">공유용 게시판</a>
            <a href="{% if user.is_authenticated %}{% url 'grow_1' %}{% else %}{% url 'login' %}{% endif %}">성장관찰</a>
            <a href="{% if user.is_authenticated %}{% url 'after_login' %}{% else %}{% url 'login' %}{% endif %}">마이페이지</a>
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">로그아웃</a>
            {% endif %}
        </nav>
    </header>
    <main>
        <a href="{% url 'main' %}">
            <img src="{% static 'img/back-button.svg' %}" alt="뒤로가기 아이콘" class="back-btn-icon">
        </a>

        <div class="Big-container">
            <div class="content-container">
                <h1 class="title-container">Title: {{ reflection.post.title }}</h1>
                <h1 class="Username-container">Username: {{ reflection.user.username }}</h1>
                <div class="black1-container">
                    <h1 class="period-container">{{ reflection.post.get_development_period_display }}</h1>
                    <h1 class="people-container">{{ reflection.post.get_participants_display }}</h1>
                </div>
                {% load myapp_filters %}
                <div class="black2-container">
                  <!-- 기술 스택을 루프를 돌면서 표시 -->
                  {% for language in reflection.post.languages.all %}
                      <h1 class="tech-container">{{ language.name }}</h1> <!-- language.name는 기술 스택의 이름을 나타냄 -->
                  {% empty %}
                      <h1 class="tech-container">No languages listed</h1>
                  {% endfor %}
              </div>
              
                <div class="img-container">
                    {% if reflection.post.file %}
                        <img src="{{ reflection.post.file.url }}" alt="{{ reflection.post.title }}의 이미지">
                    {% else %}
                        <img src="{% static 'img/default_project_image.png' %}" alt="기본 이미지">
                    {% endif %}
                </div>
                <div class="explain-container">{{ reflection.content }}</div>
            </div>

            <div class="proreflect-container">
                <h1 class="proTitle-container">회고: {{ reflection.post.title }}</h1>
                <div class="addition-info">
                    <div id="edit-delete-buttons">
                        <button>수정하기</button>
                        <button>삭제하기</button>
                    </div>
                    <div class="date-container">{{ reflection.created_at|date:"Y.m.d" }}</div>
                    <div class="reflect-container">
                        <h1 class="reflecttext-container">{{ reflection.content }}</h1>
                    </div>
                </div>
            </div>     
        </div>
    </main>
</body>
</html>